version: '3.6'
services:
  web:
    image: suryakencana007/web-todo:latest
    ports:
      - "9099:9099"
    volumes:
      - ./web/static:/static

  nginx:
    image: nginx:latest
    ports:
      - "8077:80"
    volumes:
      - ./config/nginx_default.conf:/etc/nginx/conf.d/default.conf
